---
on:
  push:

jobs:
  github_app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      token: ${{ steps.get_token.outputs.token }}
    steps:
      - name: install jwt-cli
        run: |
          curl -LO https://github.com/mike-engel/jwt-cli/releases/download/5.0.3/jwt-linux.tar.gz && \
          tar -xzf jwt-linux.tar.gz
      - name: get token
        id: get_token
        run: |
          echo "${{ secrets.private_key }}" > /tmp/jwt
          jwt=$(./jwt encode --alg RS256 --iss 349831 --secret @/tmp/jwt --exp "+5 min")
          
          installation_id="$(curl --location --silent --request GET \
            --url "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/installation" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${jwt}" \
            | jq -r '.id'
          )"
          
          token="$(curl --location --silent --request POST \
            --url "${GITHUB_API_URL}/app/installations/${installation_id}/access_tokens" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${jwt}" \
            | jq -r '.token'
          )"
          
          echo "token=$token" >> $GITHUB_OUTPUT
  